declare module 'react-syntax-highlighter'
declare module 'react-syntax-highlighter/dist/esm/styles/prism'
declare module 'react-syntax-highlighter/dist/esm/languages/prism/python'
declare module 'react-syntax-highlighter/dist/esm/languages/prism/javascript'
declare module 'react-syntax-highlighter/dist/esm/languages/prism/typescript'
declare module 'react-syntax-highlighter/dist/esm/languages/prism/json'
declare module 'react-syntax-highlighter/dist/esm/languages/prism/markdown'
declare module 'react-syntax-highlighter/dist/esm/languages/prism/bash'
