"""织光 (ZhiGuang) - Code Execution Worker（LLM 生成代码并在受限沙箱中执行）。"""

import asyncio
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from async_worker_base import AsyncWorkerBase, AsyncRegistry, AsyncMessaging


class CodeExecutionWorker(AsyncWorkerBase):
    """生成 Python 代码并在临时沙箱目录中执行，超时 60 秒。"""

    _class_capabilities = ["code_execution"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.workspace = Path(tempfile.gettempdir()) / "agent_workspace" / "code"
        self.workspace.mkdir(parents=True, exist_ok=True)

    async def execute(self, instruction: str) -> str:
        try:
            llm_response = await self._call_llm(
                instruction=(
                    "Write a single self-contained Python script that satisfies: "
                    f"{instruction}. Output ONLY the code."
                )
            )
            if not llm_response or not llm_response.strip():
                raise RuntimeError("No code generated by LLM")

            # 去掉可能的 markdown 代码块包裹
            code = llm_response.strip()
            if code.startswith("```"):
                lines = code.splitlines()
                if lines and lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                code = "\n".join(lines)

            with tempfile.NamedTemporaryFile(
                dir=self.workspace, suffix=".py", mode="w", delete=False, encoding="utf-8"
            ) as tmp_file:
                tmp_file.write(code)
                tmp_path = tmp_file.name

            try:
                proc = await asyncio.create_subprocess_exec(
                    sys.executable,
                    tmp_path,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    cwd=str(self.workspace),
                )
                stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=60)
                out = stdout.decode("utf-8", errors="replace")
                err = stderr.decode("utf-8", errors="replace")
                result = out if out else err
                return result[:2000] if result else "No output"
            finally:
                try:
                    os.unlink(tmp_path)
                except Exception:
                    pass
        except Exception as exc:
            raise RuntimeError(f"Code execution failed: {exc}") from exc


async def amain():
    from logging_setup import setup_logging
    setup_logging("worker-code-execution")
    registry = AsyncRegistry(os.environ.get("REGISTRY_DB", "agents.db"))
    messaging = AsyncMessaging(
        os.environ.get("REDIS_HOST", "localhost"),
        int(os.environ.get("REDIS_PORT", "6379")),
    )
    worker = CodeExecutionWorker(
        agent_id="codeexecworker",
        capabilities=CodeExecutionWorker._class_capabilities,
        registry=registry,
        messaging=messaging,
        max_concurrency=3,
    )
    try:
        await worker.run()
    except KeyboardInterrupt:
        await worker.shutdown()


def main():
    try:
        asyncio.run(amain())
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
