"""织光 (ZhiGuang) - Code Execution Worker。

生成并运行 Python 脚本；与 file_io 共享 project 工作区，生成的主文件
（如 main.py）会持久化保存，不再跑完即删，保证交付物真实落盘。
"""

import asyncio
import json
import os
import re
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from async_worker_base import AsyncWorkerBase, AsyncRegistry, AsyncMessaging


class CodeExecutionWorker(AsyncWorkerBase):
    _class_capabilities = ["code_execution"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.workspace = Path(tempfile.gettempdir()) / "agent_workspace" / "project"
        self.workspace.mkdir(parents=True, exist_ok=True)

    def _clean_env(self) -> dict:
        """执行环境剥离密钥类变量，防止被生成的代码读取。"""
        secrets = ("LLM_", "OPENAI_", "EMBEDDING_", "API_KEY", "SERPAPI", "TOKEN", "SECRET")
        return {k: v for k, v in os.environ.items() if not any(s in k.upper() for s in secrets)}

    def _target_filename(self, instruction: str) -> str:
        """从指令中提取目标文件名；仅当指令明确要求生成/创建/编写时才用该名字，
        否则用带时间戳的唯一名字，避免把测试脚本覆盖到 main.py。"""
        if any(k in instruction for k in ("生成", "创建", "写出", "保存为")):
            m = re.search(r"([\w\-.]+\.py)", instruction)
            if m:
                return m.group(1)
        return f"generated_{int(time.time() * 1000)}.py"

    async def execute(self, instruction: str) -> str:
        try:
            llm_response = ""
            for _gen in range(4):
                try:
                    if _gen >= 2:
                        # 前两次失败后改用极简提示，规避模型空响应/拒绝
                        llm_response = await self._call_llm(
                            system="You are a Python expert. Write minimal runnable code. Output ONLY code.",
                            prompt=(
                                "Write minimal runnable Python code (<=200 lines) that satisfies: "
                                f"{instruction[:800]}"
                            ),
                        )
                    else:
                        llm_response = await self._call_llm(
                            system=(
                                "You are a senior Python developer. Generate complete, runnable, "
                                "self-contained Python code. Output ONLY the code, no explanations."
                            ),
                            prompt=(
                                "请生成满足以下要求的完整可运行 Python 代码（自包含、可直接执行，"
                                "必要依赖仅在注释中说明）：\n"
                                f"{instruction}"
                            ),
                        )
                except Exception:
                    llm_response = ""
                    continue
                if llm_response and llm_response.strip():
                    break
            if not llm_response or not llm_response.strip():
                raise RuntimeError("No code generated by LLM")

            # 去掉可能的 markdown 代码块包装
            code = llm_response.strip()
            if code.startswith("```"):
                lines = code.splitlines()
                if lines and lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                code = "\n".join(lines)

            # 持久化：主文件用目标名，测试脚本用唯一名；避免覆盖已存在的交付物
            filename = self._target_filename(instruction)
            path = self.workspace / filename
            if path.exists():
                stem, ext = path.stem, path.suffix
                path = self.workspace / f"{stem}_{int(time.time())}{ext}"
            path.write_text(code, encoding="utf-8")

            try:
                proc = await asyncio.create_subprocess_exec(
                    sys.executable,
                    str(path),
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    cwd=str(self.workspace),
                    env=self._clean_env(),
                )
                stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=120)
                out = stdout.decode("utf-8", errors="replace")
                err = stderr.decode("utf-8", errors="replace")
                output = out if out else err
                return json.dumps({
                    "status": "success",
                    "path": str(path),
                    "filename": path.name,
                    "output": output[:3000] if output else "No output",
                    "returncode": proc.returncode,
                }, ensure_ascii=False)
            except asyncio.TimeoutError:
                proc.kill()
                raise RuntimeError("Code execution timed out after 120s")
        except Exception as exc:
            raise RuntimeError(f"Code execution failed: {exc}") from exc


async def amain():
    from logging_setup import setup_logging
    setup_logging("worker-code-execution")
    registry = AsyncRegistry(os.environ.get("REGISTRY_DB", "agents.db"))
    messaging = AsyncMessaging(
        os.environ.get("REDIS_HOST", "localhost"),
        int(os.environ.get("REDIS_PORT", "6379")),
    )
    worker = CodeExecutionWorker(
        agent_id="codeexecworker",
        capabilities=CodeExecutionWorker._class_capabilities,
        registry=registry,
        messaging=messaging,
        max_concurrency=3,
    )
    try:
        await worker.run()
    except KeyboardInterrupt:
        await worker.shutdown()


def main():
    try:
        asyncio.run(amain())
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
